- name: Demo PowerProtect Data Manager MSSQL agent deployment
  hosts: "{{ ansible_play_batch }}"
  gather_facts: false
  become: no

  vars_files:
    - vars/credentials.yml
  vars:

  tasks:
# DOWNLOAD THE SQL AGENT FROM ANSIBLE
  - name: Copy file MSSQL agent to the clients
    win_copy:
      src: "{{artifact_path}}/{{sql_agent}}"
      dest: C:\Windows\Temp\
    
# PERFROM A SILENT INSTALL OF THE AGENT
  - name: Install the MSSQL agents
    win_command: C:\Windows\Temp\{{sql_agent}} -silent -log "C:\Windows\Temp\emcappagent-19.11.0.0_install.log" InstallPPDMAgentCheckBox=1 InstallPPDMAgent=1 PPDMHostname="{{ppdm_host}}.{{ad_domain}}" EnableSSMS=1 EnableCLR=1
    register: install_status
  
  - name:
    debug:
      var: install_status

# DELETE THE INSTALLER IF IT EXISTS
  - name: Delete the MSSQL agent installer C:\Windows\Temp\{{sql_agent}}
    win_file:
      path: C:\Windows\Temp\{{sql_agent}}
      state: absent
    register: cleanup
  
  - name:
    debug:
      var: cleanup